# Generated by Django 4.2 on 2023-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="latitudine",
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="longitudine",
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
