# Generated by Django 4.2 on 2023-04-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cinema_api", "0002_alter_cinema_latitudine_alter_cinema_longitudine"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="posti_massimi",
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prenotazione",
            name="posto",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="sala",
            name="numero",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name="GestoreCinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema_api.cinema",
                    ),
                ),
                (
                    "gestore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("cinema", "gestore")},
            },
        ),
    ]
