# Generated by Django 4.2 on 2023-04-19 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema_api", "0006_alter_film_regista"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prenotazione",
            unique_together=set(),
        ),
    ]
