# Generated by Django 4.2 on 2023-04-21 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cinema_api", "0007_alter_prenotazione_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GestoreCinema",
            new_name="Gestore",
        ),
        migrations.AlterField(
            model_name="cinema",
            name="latitudine",
            field=models.DecimalField(db_index=True, decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="longitudine",
            field=models.DecimalField(db_index=True, decimal_places=17, max_digits=20),
        ),
    ]
